name: TEST DEFINITIVO

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TEST
        run: |
          echo "########################################"
          echo "QUESTO E' IL NUOVO WORKFLOW"
          echo "########################################"

          echo "COMMIT:"
          git rev-parse HEAD

          echo "PYTHON:"
          python --version

          echo "WORKFLOW:"
          cat .github/workflows/run_bot.yml

          echo "WORKFLOW PRESENTI:"
          find .github/workflows -type f -maxdepth 1 -print

          echo "RICERCA pandas_ta:"
          grep -Rni "pandas_ta" . --exclude-dir=.git || true

          echo "RICERCA requirements:"
          grep -Rni "requirements.txt" .github --exclude-dir=.git || true
